<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <AssemblyName>ascended-ezwondroustails</AssemblyName>
    <Description>Adds row probabilities to the Wondrous Tails display.</Description>
    <Authors>daemitus,MidoriKami,jkleinne</Authors>
    <Version>1.0.0.0</Version>
    <PackageProjectUrl>https://github.com/jkleinne/ascended-EzWondrousTails</PackageProjectUrl>
    <NoWarn>$(NoWarn);MSB3277</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WondrousTailsSolver.Core\WondrousTailsSolver.Core.csproj" />
  </ItemGroup>
</Project>
